### ISSUE TITLE
Question on R2D2 concept & implementation

### ISSUE THREAD

**Issue by turmeric-blend** [google-research/seed_rl#13]
Hi I hope I can ask a question here regarding R2D2 implementation as I can't find any other complete source code on R2D2 (I dont think the authors made it public? not sure)

anyway,

does [this comment](https://github.com/google-research/seed_rl/blob/eff7aaa7ab5843547fbf383fcc747b7a8ca67632/atari/networks.py#L209) imply that for one training batch with sequence length (unroll_length - burn_in + 1), **this batch might contain sequences from more than one episode?** (ie. one episode ends and another one begins) Thus, we need to reset the agent state to zero before passing to the network? and this 'reset' is performed by this line?:
```
# If the episode ended, the frame state should be reset before the next.
state = tf.nest.map_structure(
        lambda x, y, done_t=done_t: tf.where(  
            tf.reshape(done_t, [done_t.shape[0]] + [1] *
                       (x.shape.rank - 1)), x, y),
        zero_state,
        state)
```

**Comment by blenderben2** [comment]
Thanks for the detailed reply! 💯

**Comment by turmeric-blend** [comment]
thanks for the clear and detailed reply! :100:

**Comment by turmeric-blend** [comment]
Hi @RaphaelMarinier I have another question regarding R2D2 concept hope thats ok, this is regarding the frame stacking method vs stored state (RNN method). 

In the [original paper](https://arxiv.org/pdf/1507.06527.pdf) that introduced the zero initial state RNN method, the paper suggested it as an alternative to the frame stacking method (although no significant benefits), and did not combine the two methods.

However in this version of R2D2 implementation, stored state (similar concept to zero state) seems to be implemented in conjunction with frame stacking. I was wondering if you knew what is the intuition behind combining them or if combining the two methods is better than not combining?

**Comment by RaphaelMarinier** [comment]
Hi @turmeric-blend,

This is a very good point.

First of all, note that the [original R2D2 paper](https://openreview.net/pdf?id=r1lyTjAqYX) uses both a recurrent net and frame stacking (implicit from sections 2.2 and 2.3).

We indeed tried not to use frame-stacking since it should not be necessary with a recurrent net. The scores achieved were still impressive (median human normalized score was higher than 1000%) but lower than with 4 frame stacks (~1900%). The score on some games was strongly affected when not using frame stacking, e.g. SpaceInvaders whose score usually "explodes" above 40k with frame stacking, but usually plateaus around 3k without.

So in the R2D2 setting, frame stacking is beneficial if you want to reach the best scores.

**Comment by turmeric-blend** [comment]
Thanks @RaphaelMarinier, this helps (:
