### ISSUE TITLE
Why "dones" need zero padding in stack_frames of R2D2?

### ISSUE THREAD

**Issue by sorryformyself** [google-research/seed_rl#59]
https://github.com/google-research/seed_rl/blob/master/atari/networks.py#L133

` done_masks = [
      tf.zeros(done_mask_row_shape, dtype=tf.bool),
      tf.reshape(done, done_mask_row_shape)
  ]`

I know that the frame that crosses an episode boundary should be zeroed out, but why "dones" should use zero padding? 

Another question is that how those "dones_masks" affect the frames. Frames are ordered from newest to oldest, and why those dones_masks can mask the corresponding frames?

Looking forward to your reply, thanks :)

**Comment by RaphaelMarinier** [comment]
[stacked_frames](https://github.com/google-research/seed_rl/blob/f53c5be4ea083783fb10bdf26f11c3a80974fa03/atari/networks.py#L123) contains the stacked frames without the episode boundaries properly zeroed out. 
[stacked_done_masks](https://github.com/google-research/seed_rl/blob/f53c5be4ea083783fb10bdf26f11c3a80974fa03/atari/networks.py#L154) allows zeroing out the episode boundaries properly (stacked_done_masks contains a 1 when the corresponding observation should be zeroed out).

Let's take an example (ignoring batch, width, height dimensions).
Say the observation is: [s0, s1, s2, s3, s4] (this is across the time dimension) and done vector is: [0, 1, 0, 0, 0]. This means that the episode was done between s0 and s1.
Let's assume stack_size=4, and denote by s(-3), s(-2), s(-1) the 3 previous frames that come from frame_stacking_state.

Then:
extended_frames will contain [s(-3), s(-2), s(-1), s0, s1, s2, s3, s4] (across the time dimension).
stacked_frames will be [time, ..., stack_size]: 
[[s0, s(-1), s(-2), s(-3)],
 [s1, s0, s(-1), s(-2)],
 [s2, s1, s0, s(-1)],
 [s3, s2, s1, s0],
 [s4, s3, s2, s1]]

Now, in each stack of frames given to the network (corresponding to a *row* in stacked_frames), we need to zero out all frames that were generated before a done (episode boundary) occurred. E.g. with a done that occurred between s1 and s0, the third row should become [s2, s1, 0, 0].

We compute the done_masks so that this happens. In our case with done=[0, 1, 0, 0, 0], stacked_done_masks has shape [time, ..., stack_size] and is:
[[0, 0, 0, 0],
 [0, 1, 1, 1],
 [0, 0, 1, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 0]]
This is computed column by column in [done_masks](https://github.com/google-research/seed_rl/blob/f53c5be4ea083783fb10bdf26f11c3a80974fa03/atari/networks.py#L132), where the first column is all 0s, second column is the done vector, and each subsequent column is the or between the previous column and the previous column shifted one position down, which corresponds to the fact that the observation to zero out advances by one position in the stack when we move by one position in time.

And finally this [tf.where](https://github.com/google-research/seed_rl/blob/f53c5be4ea083783fb10bdf26f11c3a80974fa03/atari/networks.py#L155) puts a zeroed observation when the stacked_done_masks has a 1.

So the result is:
[[s0, s(-1), s(-2), s(-3)],
 [s1, 0, 0, 0],
 [s2, s1, 0, 0, ],
 [s3, s2, s1, 0],
 [s4, s3, s2, s1]]

Hope this helps.

**Comment by sorryformyself** [comment]
@RaphaelMarinier  Thanks for your kindly reply, this really helps me a lot, You're a good teacher!

Now i know how it works, the implementation was quite cool!  ^_^
