### ISSUE TITLE
Is the gcp/train_atari.sh script actually using one GPU device for training? 

### ISSUE THREAD

**Issue by bingykang** [google-research/seed_rl#62]
According to the script https://github.com/google-research/seed_rl/blob/master/gcp/train_atari.sh#L32-L39, it requires two NVIDIA_TESLA_P100 gpu. 

But in this script https://github.com/google-research/seed_rl/blob/master/common/utils.py#L99, when there are not TPU devices, it will adopt OneDeviceStrategy for learning. 

So, this gcp/train_atari.sh script is actually the same as running seed rl in a local manner?

**Comment by lespeholt** [comment]
I believe you're right about that. E.g. see the comment just before:
# n1-highmem-32 provides 208GBs of RAM, n1-highmem-16 provides 104GBS.
# Training on ATARI requires a bit more than 104GBs due to the large replay
# buffer, so we need n1-highmem-32, which requires 2 GPUs (see  # https://cloud.google.com/ml-engine/docs/using-gpus).

One could arguably use the two GPUs efficiently instead of wasting one.
